upgrade to pingfederate 9.2

diff --git a/templates/default/run_sh.erb b/templates/default/run_sh.erb
--- a/templates/default/run_sh.erb
+++ b/templates/default/run_sh.erb
@@ -1,19 +1,20 @@
 #!/usr/bin/env bash
-# Dropped off by CHEF!
 ### ====================================================================== ###
 ##                                                                          ##
 ##  PingFederate Bootstrap Script                                           ##
 ##                                                                          ##
 ### ====================================================================== ###
+# Dropped off by Chef!
+<% if @java_home %>
+	JAVA_HOME=<%= @java_home %>
+	export JAVA_HOME
+<% end %>
 
 ### $Id: run.sh,v 1.19.4.2 2004/12/15 16:54:03 starksm Exp $ ###
-<% if @java_home %>
-export JAVA_HOME=<%= @java_home %>
-<% end %>
-export PATH=$PATH:$JAVA_HOME/bin
 
-DIRNAME=`dirname $0`
-PROGNAME=`basename $0`
+
+DIRNAME=`dirname "$0"`
+PROGNAME=`basename "$0"`
 GREP="grep"
 
 # Use the maximum available, or set MAX_FD != -1 to use that
@@ -47,14 +48,14 @@ case "`uname`" in
     Darwin*)
         darwin=true
         ;;
-        
+
     Linux*)
         linux=true
         ;;
-        
+
     SunOS*)
         sunos=true
-        ;;        
+        ;;
 esac
 
 # Read an optional running configuration file
@@ -76,7 +77,7 @@ fi
 # Setup PF_HOME
 if [ "x$PF_HOME" = "x" ]; then
     # get the full path (without any relative bits)
-    PF_HOME=`cd $DIRNAME/..; pwd`
+    PF_HOME=`cd "$DIRNAME/.."; pwd`
 fi
 export PF_HOME
 
@@ -105,36 +106,39 @@ fi
 if [ "$cygwin" = "false" ]; then
     MAX_FD_LIMIT=`ulimit -H -n`
     if [ $? -eq 0 ]; then
-	if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ]; then
-	    # use the system max
-	    MAX_FD="$MAX_FD_LIMIT"
-	fi
+    if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ]; then
+        # use the system max
+        MAX_FD="$MAX_FD_LIMIT"
+    fi
 
         if [ "$darwin" = "false" ]; then
             ulimit -n $MAX_FD
             if [ $? -ne 0 ]; then
                  warn "Could not set maximum file descriptor limit: $MAX_FD"
             fi
-        else
-	    # OS X is set to unlimited by default 
-            /bin/echo "Maximum file descriptor limit: `ulimit -H -n`"
         fi
-
     else
-	warn "Could not query system maximum file descriptor limit: $MAX_FD_LIMIT"
+    warn "Could not query system maximum file descriptor limit: $MAX_FD_LIMIT"
     fi
 fi
 
 # Setup the JVM
 if [ "x$JAVA" = "x" ]; then
     if [ "x$JAVA_HOME" != "x" ]; then
-	    JAVA="$JAVA_HOME/bin/java"
+        if ! [ -n "$JAVA_HOME" ] || ! [ -x "$JAVA_HOME/bin/java" ];  then
+            echo "No executable java found in JAVA_HOME, please correct and start PingFederate again. Exiting."
+            exit 1
+        fi
+        JAVA="$JAVA_HOME/bin/java"
     else
-	    JAVA="java"
+        JAVA="java"
         warn "JAVA_HOME is not set.  Unexpected results may occur."
         warn "Set JAVA_HOME to the directory of your local JDK or JRE to avoid this message."
     fi
 fi
+
+JAVA_VERSION=`"$JAVA" -version 2>&1 | grep "version" | head -n 1 | cut -d\" -f 2 `
+JAVA_MAJOR_VERSION=`echo ${JAVA_VERSION/_/.} | cut -d. -f 1`
 
 # Setup the classpath
 runjar="$PF_HOME/bin/run.jar"
@@ -151,11 +155,11 @@ if [ ! -f "$jettystartjar" ]; then
 fi
 xmlbeans="$PF_HOME/server/default/lib/xmlbeans.jar"
 if [ ! -f "$xmlbeans" ]; then
-	die "Missing required file: $xmlbeans"
+    die "Missing required file: $xmlbeans"
 fi
 pfxml="$PF_HOME/server/default/lib/pf-xml.jar"
 if [ ! -f "$pfxml" ]; then
-	die "Missing required file: $pfxml"
+    die "Missing required file: $pfxml"
 fi
 
 pf_console_util="$PF_HOME/bin/pf-consoleutils.jar"
@@ -174,124 +178,47 @@ if [ "x$JAVA_OPTS" = "x" ]; then
 
     # Check for SUN(tm) JVM w/ HotSpot support
     if [ "x$HAS_HOTSPOT" = "x" ]; then
-	HAS_HOTSPOT=`$JAVA -version 2>&1 | $GREP -i HotSpot`
+    HAS_HOTSPOT=`$JAVA -version 2>&1 | $GREP -i HotSpot`
     fi
 
     # Enable -server if we have Hotspot, unless we can't
     if [ "x$HAS_HOTSPOT" != "x" ]; then
-	# MacOS does not support -server flag
-	if [ "$darwin" != "true" ]; then
-	    JAVA_OPTS="-server"
-	fi
+    # MacOS does not support -server flag
+    if [ "$darwin" != "true" ]; then
+        JAVA_OPTS="-server"
+    fi
     fi
 fi
 
-#JVM Optimizations (for non MacOSX) systems based on system resources. Modify as appropriate.
+# JVM Optimizations
+# To configure JVM options please edit jvm-memory.options in
+# <install-dir>/pingfederate/bin
 
-totalMem=0
-numberCPUCores=1
-minimumHeap="-Xms256m"
-maximumHeap="-Xmx1024m"
-minimumPermSize="-XX:PermSize=96m"
-minimumNewSize=""
-maximumNewSize=""
-garbageCollector=""
+jvmmemoryopts="$PF_HOME/bin/jvm-memory.options"
 
-if [ "$darwin" != "true" ]; then
-	
-	if [ "$linux" = "true" ]; then	
-		totalMem=`free -t | grep "cache:" | awk '{ print $4}'`
-		if [ "$totalMem" = "" ]; then
-                        totalMem=`free -t | grep "Mem:" | awk '{ print $4+$6}'`
-                fi
-		numberCPUCores=`cat /proc/cpuinfo | grep "processor" | wc -l`
-	fi
-	
-	if [ "$sunos" = "true" ]; then
-		totalMem=`vmstat | awk 'NR==3{print $5}'`
-		numberCPUCores=`kstat cpu_info | grep -w core_id | awk '{ print $2}' |  wc -l`
-	fi
-
-	if [ $totalMem -ge 2621440 ]; then
-  		minimumHeap="-Xms2048m"
-		maximumHeap="-Xmx2048m"
-		minimumNewSize="-XX:NewSize=1024m"
-		maximumNewSize="-XX:MaxNewSize=1024m"
-	elif [ $totalMem -ge 2097152 ]; then
-  		minimumHeap="-Xms1536m"
-		maximumHeap="-Xmx1536m"
-		minimumNewSize="-XX:NewSize=768m"
-		maximumNewSize="-XX:MaxNewSize=768m"	
-	else
-  		minimumHeap="-Xms256m"
-		maximumHeap="-Xmx1024m"
-	fi
-
-	if [ $numberCPUCores -ge 2 ]; then
-		garbageCollector="-XX:+UseParallelOldGC"
-	fi
+# Check for jvm-memory.options (used by PingFederate to set JVM memory settings)
+if [ ! -f "$jvmmemoryopts" ]; then
+    die "Missing $jvmmemoryopts"
 fi
 
-# If you want to override resource-based JVM configuration, you may do so below.
-# Use caution as incorrect values may prevent PingFederate from starting or running.
-# Please refer to the HotSpot(tm) VM Options article on the Oracle(tm) website at:
-# www.oracle.com/technetwork/java/javase/tech/vmoptions-jsp-140102.html
-# or to the PingFederate Tuning Guide available on the Customer Portal at www.pingidentity.com.
-#
-# It is recommended that minimumHeap and maximumHeap be assigned values.
-# in most cases minimumPermSize need not be modified and it is not used in JDK 8.
-# It is valid to leave minimumNewSize, maximumNewSize and garbageCollector blank.
-#
-# Examples:
-# Set 256 mb as minimum size for the young generation: minimumNewSize="-XX:NewSize=256m"
-# Set 256 mb as maximum size for the young generation: maximumNewSize="-XX:MaxNewSize=256m"
-#
-# Valid values for garbage collector are:
-# garbageCollector= (allows JVM to select garbage collector based on Heap and CPU resources)
-# garbageCollector="-XX:+UseG1GC"  (enables Garbage First Collector)
-# garbageCollector="-XX:-UseParallelGC (enables Parallel Young, Serial Old Collector) 
-# garbageCollector="-XX:-UseParallelOldGC (uses Parallel Young and Parallel Old Collector)
-# garbageCollector="-XX:-UseConcMarkSweepGC (use Concurrent Mark Sweep collector)
+#Setup JVM Heap optimizations
+JVM_MEMORY_OPTS=
+allDone=false
+until $allDone; do
+    #Read every line. Last line might return a non-zero exit code if not followed by a new line, but still reads the line.
+    read -r line || allDone=true
+    #Filter empty and commented lines
+    ( [[ $line =~ ^#.*$ ]] || [[ -z $line ]] ) && continue
+    JVM_MEMORY_OPTS="$JVM_MEMORY_OPTS $line"
+done < "$jvmmemoryopts"
 
-# For manual configuration, remove the preceding "#" and apply values between quotes.
-#
-# minimumHeap="-Xms256m"
-# maximumHeap="-Xmx1024m"
-# minimumPermSize="-XX:PermSize=96m" 
-# minimumNewSize=""
-# maximumNewSize=""
-# garbageCollector=""
-
-JAVA_FULL_VERSION=`"$JAVA" -version 2>&1 | head -1 | cut -d '"' -f2`
-JAVA_MINOR_VERSION=`/bin/echo ${JAVA_FULL_VERSION} | cut -d "." -f2`
-
-if [ "$JAVA_MINOR_VERSION" -le "6" ]; then
-  /bin/echo "PingFederate must be run using Java 1.7 or higher.  Exiting."
-    exit 1
-fi
-
-if [ "$JAVA_MINOR_VERSION" = "8" ]; then
-  minimumPermSize=""
-fi
-
-JAVA_OPTS="$JAVA_OPTS $minimumHeap $maximumHeap $minimumPermSize"
-
-if [ "$darwin" != "true" ]; then 
-	if [ "$minimumNewSize" != "" ]; then
-  		JAVA_OPTS="$JAVA_OPTS $minimumNewSize"
-	fi
-
-	if [ "$maximumNewSize" != "" ]; then
-  		JAVA_OPTS="$JAVA_OPTS $maximumNewSize"
-	fi
-
-	if [ "$garbageCollector" != "" ]; then
-  		JAVA_OPTS="$JAVA_OPTS $garbageCollector"
-	fi
-fi
+JAVA_OPTS="$JAVA_OPTS $JVM_MEMORY_OPTS"
 
 # Setup PingFederate specific properties
 JAVA_OPTS="$JAVA_OPTS -Dprogram.name=$PROGNAME"
+
+RANDOM_SOURCE="-Djava.security.egd=file:/dev/./urandom"
+JAVA_OPTS="$JAVA_OPTS $RANDOM_SOURCE"
 
 # Workaround for nCipher HSM to support Java 8
 # Remove this when nCipher officially supports Java 8
@@ -303,8 +230,17 @@ JAVA_OPTS="$JAVA_OPTS -Dcom.ncipher.provider.announcemode=on"
 # Debugger arguments
 #JAVA_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=y $JAVA_OPTS"
 
+# disable use of preallocated exceptions and always show the full stacktrace
+JAVA_OPTS="$JAVA_OPTS -XX:-OmitStackTraceInFastThrow"
+
 # Setup the java endorsed dirs
 PF_ENDORSED_DIRS="$PF_HOME/lib/endorsed"
+
+#comment out to disable java crash logs
+ERROR_FILE="-XX:ErrorFile=$PF_HOME_ESC/log/java_error%p.log"
+
+#uncomment to enable Memory Dumps
+#HEAP_DUMP="-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=$PF_HOME_ESC/log"
 
 # For Cygwin, switch paths to Windows format before running java
 if $cygwin; then
@@ -312,6 +248,11 @@ if $cygwin; then
     JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
     PF_CLASSPATH=`cygpath --path --windows "$PF_CLASSPATH"`
     PF_ENDORSED_DIRS=`cygpath --path --windows "$PF_ENDORSED_DIRS"`
+fi
+
+ENDORSED_DIRS_FLAG=``
+if [ "$JAVA_MAJOR_VERSION" = "1" ]; then
+    ENDORSED_DIRS_FLAG='-Djava.endorsed.dirs="$PF_ENDORSED_DIRS"'
 fi
 
 # Check for run.properties (used by PingFederate to configure ports, etc.)
@@ -329,9 +270,13 @@ while [ $STATUS -eq 10 ]
 do
 # Execute the JVM
    "$JAVA" $JAVA_OPTS \
+   	  $ERROR_FILE \
+   	  $HEAP_DUMP \
+      $ENDORSED_DIRS_FLAG \
+   	  -Dlog4j2.AsyncQueueFullPolicy=Discard \
+   	  -Dlog4j2.DiscardThreshold=INFO \
       -Dlog4j.configurationFile="$PF_HOME_ESC/server/default/conf/log4j2.xml" \
       -Drun.properties="$runprops" \
-      -Djava.endorsed.dirs="$PF_ENDORSED_DIRS" \
       -Dpf.home="$PF_HOME" \
       -Djetty.home="$PF_HOME" \
       -Djetty.base="$PF_HOME/bin" \
